### ISSUE TITLE
Regression in german translation?

### ISSUE THREAD

**Issue by ihew** [Whisky-App/WhiskySite#35]
I originally updated a few entries on the crowdin site back then (consistently changed the entries from the more formal german for of address to "you" and use of the correct imperative forms etc.) and thought that they actually made it into the site project afterwards already 

Seems that was reverted for certain entries during the transfer into github. 

Not that I would insist on "my" proposals... Just that I checked and saw some of those small inconsistencies had came back. Not sure if on purpose or accidentally. (Not sure if I always used the right edit mode on crowdin back then either, though).

**Comment by IsaacMarovitz** [comment]
You can always go back and re-add your edits on Crowdin
