### ISSUE TITLE
The Discord inviting link in the website has expired

### ISSUE THREAD

**Issue by noobnooc** [Whisky-App/WhiskySite#72]
I want to join the Discord group, but when I click the link on the website, it notice me that the link has expired.

**Comment by JoshuaBrest** [comment]
https://discord.gg/whisky-1115955071549702235

**Comment by noobnooc** [comment]
> https://discord.gg/whisky-1115955071549702235

Thanks, finally I found out that it's caused by my browser, all discord links will be prompted as expired.
